receivers:
  prometheus:
      config:
        scrape_configs:
          - job_name: 'prom-metric-test-app'
            scrape_interval: 10s
            static_configs:
              - targets: ['metrics-producer-app:8080']

exporters:
  prometheus:
    endpoint: otel-collector:1234

extensions:
  health_check:
  pprof:
  zpages:

service:
  extensions: [health_check, pprof, zpages]
  pipelines:
    metrics:
      receivers: [prometheus]
      processors: []
      exporters: [prometheus]